# Numpy入门[6]——数组排序

> 参考：
>
> [https://ailearning.apachecn.org/](https://ailearning.apachecn.org/)
>
> 使用Jupyter进行练习

In [24]:
import numpy as np

## sort函数

In [25]:
names = np.array(['i','yjq','love','you'])
weights = np.array([20.8, 93.2, 53.4, 90.8])
np.sort(names)

array(['i', 'love', 'yjq', 'you'], dtype='<U4')

sort 返回的结果是从小到大排列的。

## argsort函数

argsort 返回从小到大的排列在数组中的索引位置，使用函数并不会改变原来数组的值。

In [26]:
order_indices = np.argsort(weights)
print(order_indices)
print(weights[order_indices])
print(names[order_indices])
print(names)

[0 2 3 1]
[20.8 53.4 90.8 93.2]
['i' 'love' 'you' 'yjq']
['i' 'yjq' 'love' 'you']


## sort 和 argsort 方法

也提供相关的方法操作

In [27]:
data = np.array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

argsort 方法与 argsort 函数的使用没什么区别，也不会改变数组的值。

In [28]:
data

array([20.8, 93.2, 53.4, 61.8])

但是 sort方法会改变数组的值：

In [29]:
data.sort()
data

array([20.8, 53.4, 61.8, 93.2])

## 二维数组排序

对于多维数组，sort方法默认沿着最后一维开始排序：


In [30]:
a = np.array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .8]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.8]])

对于二维数组，默认相当于对每一行进行排序：

In [31]:
np.sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.8, 0.9]])

改变轴，对每一列进行排序：

In [33]:
np.sort(a,axis=0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.8]])

## searchsorted 函数

```python
searchsorted(sorted_array, values) 
```
searchsorted 接受两个参数，其中，第一个必需是已排序的数组。

In [37]:
sorted_array = np.linspace(0,1,5)
values = np.array([.1,.8,.3,.12,.5,.25])
sorted_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
np.searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

排序数组：

| 0    | 1    | 2    | 3    | 4    |
| ---- | ---- | ---- | ---- | ---- |
| 0.0  | 0.25 | 0.5  | 0.75 | 1.0  |

数值：

| 值       | 0.1  | 0.8  | 0.3  | 0.12 | 0.5  | 0.25 |
| -------- | ---- | ---- | ---- | ---- | ---- | ---- |
| 插入位置 | 1    | 4    | 2    | 1    | 2    | 1    |



searchsorted 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

例如 0.1 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 1 处，故第一个返回值为 1。


例子，取处于某个区间的所有元素。

In [42]:
from numpy.random import rand
data = rand(100)
data.sort()
bounds = .4, .6
bounds
# 返回这两个值对应的插入位置：
low_idx, high_idx = np.searchsorted(data, bounds)
# 利用插入位置，将数组中所有在这两个值之间的值提取出来：
data[low_idx:high_idx]


array([0.40630023, 0.42214576, 0.4495508 , 0.46038062, 0.46424695,
       0.46829198, 0.46952976, 0.48215567, 0.50312859, 0.50993821,
       0.53333557, 0.54154817, 0.565134  , 0.58349009, 0.5877485 ,
       0.59070813, 0.59234286, 0.59346449, 0.59363681, 0.59413639])