# Numpy入门[7]——数组形状

> 参考：
>
> [https://ailearning.apachecn.org/](https://ailearning.apachecn.org/)
>
> 使用Jupyter进行练习

In [1]:
import numpy as np

## 修改数组的形状

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

将形状修改为2 x 3

In [3]:
a.shape = 2 , 3
a

array([[0, 1, 2],
       [3, 4, 5]])

与之对应的方法是 `reshape` ，但它不会修改原来数组的值，而是返回一个新的数组：

In [4]:
a.reshape(3 , 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

`shape` 和 `reshape` 方法不能改变数组中元素的总数，否则会报错：

## 使用newaxis增加数组维数 

In [7]:
b = np.arange(3)
np.shape(b)

(3,)

In [8]:
c = b[np.newaxis, : ]
np.shape(c)

(1, 3)

根据插入位置的不同，可以返回不同形状的数组：

In [9]:
d = b[ : , np.newaxis]
np.shape(d)

(3, 1)

也可以插入多个新维度：

In [11]:
e = b[np.newaxis, np.newaxis, :]
np.shape(e)

(1, 1, 3)

## squeeze方法去除多余的轴

squeeze 返回一个将所有长度为1的维度去除的新数组。

In [12]:
a = np.arange(6)
a.shape = (2, 1, 3)
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [13]:
b = a.squeeze()
b.shape

(2, 3)

## 数组转置

使用`transpose`返回数组的转置，本质上是将所有维度反过来。

In [14]:
a = np.arange(6)
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

或者使用缩写属性：

In [16]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

**注意**：

+ 对于复数数组，转置并不返回复共轭，只是单纯的交换轴的位置

+ 转置可以作用于多维数组

另一方面，转置返回的是对原数组的另一种view，所以改变转置会改变原来数组的值。

## 数组连接

有时我们需要将不同的数组按照一定的顺序连接起来：
```python
concatenate((a0,a1,...,aN) , axis = 0)
```

注意，这些数组要用 () 包括到一个元组中去。

除了给定的轴外，这些数组其他轴的长度必须是一样的。

In [17]:
x = np.array([
    [0, 1, 2],
    [10, 11, 12]
])
y = np.array([
    [50, 51, 52],
    [60, 61, 62]
])
print(x.shape)
print(y.shape)


(2, 3)
(2, 3)


默认沿着第一维进行连接：

In [19]:
z = np.concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

沿着第二维进行连接：

In [21]:
z = np.concatenate((x,y), axis = 1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

注意到这里 x 和 y 的形状是一样的，还可以将它们连接成三维的数组，但是 concatenate 不能提供这样的功能，不过可以这样：

In [23]:
z = np.array((x,y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

In [24]:
z.shape

(2, 2, 3)

事实上，Numpy提供了分别对应这三种情况的函数：

+ vstack

+ hstack

+ dstack

In [27]:
print(np.vstack((x,y)))
print(np.hstack((x,y)))
print(np.dstack((x,y)))

[[ 0  1  2]
 [10 11 12]
 [50 51 52]
 [60 61 62]]
[[ 0  1  2 50 51 52]
 [10 11 12 60 61 62]]
[[[ 0 50]
  [ 1 51]
  [ 2 52]]

 [[10 60]
  [11 61]
  [12 62]]]


## flatten数组

### flatten 方法

`flatten` 方法的作用是将多维数组转化为1维数组：

In [28]:
a = np.array([[0,1],
           [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

返回的是数组的复制，因此，改变 b 并不会影响 a 的值：

### flat属性

还可以使用数组自带的`flat` 属性：

In [29]:
a.flat

a.flat 相当于返回了所有元组组成的一个迭代器：

In [31]:
b = a.flat
b[0]

0

但此时修改 b 的值会影响 a ：

In [32]:
b[0] = 520
print(a)

[[520   1]
 [  2   3]]


In [33]:
a.flat[:]

array([520,   1,   2,   3])

### ravel方法

除此之外，还可以使用 ravel 方法，ravel 使用高效的表示方式：

In [34]:
a = np.array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

修改 b 会改变 a 。

## atleast_xd 函数

保证数组至少有 x 维：x 可以取值 1，2，3。

In [35]:
x = 1
np.atleast_1d(x)

array([1])

In [36]:
a = np.array([1,2,3])
b = np.atleast_2d(a)
b.shape

(1, 3)

In [37]:
b

array([[1, 2, 3]])

In [38]:
c = np.atleast_3d(b)
c.shape

(1, 3, 1)