# Numpy入门[8]——对角线

> 参考：
>
> [https://ailearning.apachecn.org/](https://ailearning.apachecn.org/)
>
> 使用Jupyter进行练习

In [1]:
import numpy as np

In [2]:
a = np.array([11,21,31,12,22,32,13,23,33])
a.shape = 3,3
a

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

查看它的对角线元素：

In [3]:
a.diagonal()

array([11, 22, 33])

可以使用偏移来查看它的次对角线，正数表示右移，负数表示左移：

In [4]:
a.diagonal(offset=1)

array([21, 32])

In [5]:
a.diagonal(offset=-1)

array([12, 23])

也可以使用花式索引获得对角线元素

In [6]:
i = [0, 1, 2]
a[i, i]

array([11, 22, 33])

可以更新对角线的值：

In [8]:
a[i,i] = 1
a

array([[ 1, 21, 31],
       [12,  1, 32],
       [13, 23,  1]])