# Numpy入门[10]——数组属性方法总结

> 参考：
>
> [https://ailearning.apachecn.org/](https://ailearning.apachecn.org/)
>
> 使用Jupyter进行练习

In [56]:
import numpy as np

## 总结

| 作用                                |                                                  |
| ----------------------------------- | ------------------------------------------------ |
| 1                                   | **基本属性**                                     |
| `a.dtype`                           | 数组元素类型 `float32,uint8,...`                 |
| `a.shape`                           | 数组形状 `(m,n,o,...)`                           |
| `a.size`                            | 数组元素数                                       |
| `a.itemsize`                        | 每个元素占字节数                                 |
| `a.nbytes`                          | 所有元素占的字节                                 |
| `a.ndim`                            | 数组维度                                         |
| 2                                   | **形状相关**                                     |
| `a.flat`                            | 所有元素的迭代器                                 |
| `a.flatten()`                       | 返回一个1维数组的复制                            |
| `a.ravel()`                         | 返回一个1维数组，高效                            |
| `a.resize(new_size)`                | 改变形状                                         |
| `a.swapaxes(axis1, axis2)`          | 交换两个维度的位置                               |
| `a.transpose(*axex)`                | 交换所有维度的位置                               |
| `a.T`                               | 转置，`a.transpose()`                            |
| `a.squeeze()`                       | 去除所有长度为1的维度                            |
| 3                                   | **填充复制**                                     |
| `a.copy()`                          | 返回数组的一个复制                               |
| `a.fill(value)`                     | 将数组的元组设置为特定值                         |
| 4                                   | **转化**                                         |
| `a.tolist()`                        | 将数组转化为列表                                 |
| `a.tostring()`                      | 转换为字符串                                     |
| `a.astype(dtype)`                   | 转化为指定类型                                   |
| `a.byteswap(False)`                 | 转换大小字节序                                   |
| `a.view(type_or_dtype)`             | 生成一个使用相同内存，但使用不同的表示方法的数组 |
| 5                                   | **复数**                                         |
| `a.imag`                            | 虚部                                             |
| `a.real`                            | 实部                                             |
| `a.conjugate()`                     | 复共轭                                           |
| `a.conj()`                          | 复共轭（缩写）                                   |
| 6                                   | **保存**                                         |
| `a.dump(file)`                      | 将二进制数据存在file中                           |
| `a.dump()`                          | 将二进制数据表示成字符串                         |
| `a.tofile(fid, sep="",format="%s")` | 格式化ASCⅡ码写入文件                             |
| 7                                   | **查找排序**                                     |
| `a.nonzero()`                       | 返回所有非零元素的索引                           |
| `a.sort(axis=-1)`                   | 沿某个轴排序                                     |
| `a.argsort(axis=-1)`                | 沿某个轴，返回按排序的索引                       |
| `a.searchsorted(b)`                 | 返回将b中元素插入a后能保持有序的索引值           |
| 8                                   | **元素数学操作**                                 |
| `a.clip(low, high)`                 | 将数值限制在一定范围内                           |
| `a.round(decimals=0)`               | 近似到指定精度                                   |
| `a.cumsum(axis=None)`               | 累加和                                           |
| `a.cumprod(axis=None)`              | 累乘积                                           |
| 9                                   | **约简操作**                                     |
| `a.sum(axis=None)`                  | 求和                                             |
| `a.prod(axis=None)`                 | 求积                                             |
| `a.min(axis=None)`                  | 最小值                                           |
| `a.max(axis=None)`                  | 最大值                                           |
| `a.argmin(axis=None)`               | 最小值索引                                       |
| `a.argmax(axis=None)`               | 最大值索引                                       |
| `a.ptp(axis=None)`                  | 最大值减最小值                                   |
| `a.mean(axis=None)`                 | 平均值                                           |
| `a.std(axis=None)`                  | 标准差                                           |
| `a.var(axis=None)`                  | 方差                                             |
| `a.any(axis=None)`                  | 只要有一个不为0，返回真，逻辑或                  |
| `a.all(axis=None)`                  | 所有都不为0，返回真，逻辑与                      |

## 基本属性

In [57]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
print("数组元素属性(dtype)：",a.dtype)
print("数组形状(shape)：",a.shape)
print("元素数目(size)：",a.size)
print("元素占字节大小(itemsize)：",a.itemsize)
print("所有元素所占字节(nbytes)：",a.nbytes)
print("数组维度(ndim)：",a.ndim)

数组元素属性(dtype)： int32
数组形状(shape)： (2, 4)
元素数目(size)： 8
元素占字节大小(itemsize)： 4
所有元素所占字节(nbytes)： 32
数组维度(ndim)： 2


## 形状相关

In [59]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]


In [60]:
# 迭代所有元素
for element in a.flat:
    print(element)

0
1
2
3
4
5
6
7


### 所有元素组成的一维数组，按照行排列

In [61]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### resize与reshape的区别


区别一：

+ resize 无返回值（返回值为None），会改变原数组。

+ reshape 有返回值，返回值是被reshape后的数组，不会改变原数组。


区别二：

+ resize 可以放大或者缩小原数组的形状：放大时，会用0补全剩余元素；缩小时，直接丢弃多余元素。

+ reshape 要求reshape前后元素个数相同，否则会报错，无法运行。

In [63]:
b = a.copy()
b.resize((4,4))
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 交换轴的顺序

In [64]:
a.swapaxes(0,1)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### 转置

In [65]:
a.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [66]:
a.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### 去除长度为一的维度


In [67]:
a2 = np.array([1,2,3])
a2.resize((1,3,1))
a2

array([[[1],
        [2],
        [3]]])

In [68]:
a2 = a2.squeeze()
a2.shape

(3,)

## 填充复制

### 复制

In [69]:
c = a.copy()
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

复制不影响原来的数组。

### 填充

In [70]:
c.fill(4)
c

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

## 转化

### 转化为列表

In [71]:
a.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7]]

### 转化为字符串

In [72]:
a.tobytes()

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00'

### 改变数组元素类型

In [73]:
a.astype(float)

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

### 交换大小字节序

In [74]:
d = a.copy()
d.byteswap()

array([[        0,  16777216,  33554432,  50331648],
       [ 67108864,  83886080, 100663296, 117440512]])

### 改变表示方式

In [75]:
a.view(dtype=np.int16)

array([[0, 0, 1, 0, 2, 0, 3, 0],
       [4, 0, 5, 0, 6, 0, 7, 0]], dtype=int16)

## 复数

In [76]:
b = np.array([1+2j, 3+4j, 5+6j])
print(b)
print("实部(real)：",b.real)
print("虚部(imag)：",b.imag)
print("共轭(conj)：",b.conj())

[1.+2.j 3.+4.j 5.+6.j]
实部(real)： [1. 3. 5.]
虚部(imag)： [2. 4. 6.]
共轭(conj)： [1.-2.j 3.-4.j 5.-6.j]


## 保存

### 保存成文本


In [77]:
a.dump("file.txt")

### 字符串

In [78]:
a.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02K\x04\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X \x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

### 写入文件

In [79]:
a.tofile('foo.csv', sep=',', format="%s")

## 查找排序

### 非零元素的索引


In [80]:
a.nonzero()

(array([0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

### 排序

In [81]:
b = np.array([3,2,7,4,1])
b.sort()
b

array([1, 2, 3, 4, 7])

### 排序的索引位置


In [82]:
b = np.array([2,3,1])
b.argsort(axis=-1)

array([2, 0, 1], dtype=int64)

### 插入索引排序

将 b 插入 a 中的索引，使得 a 保持有序：

In [55]:
a = np.array([1,3,4,6])
b = np.array([0,2,5])
a.searchsorted(b)

array([0, 1, 3], dtype=int64)

## 元素数学操作

### 限制在一定范围

In [83]:
a = np.array([[4,1,3],[2,1,5]])
a.clip(0,2)

array([[2, 1, 2],
       [2, 1, 2]])

### 近似

In [84]:
a = np.array([1.344, 2.449, 2.558])
a.round(decimals=2)

array([1.34, 2.45, 2.56])

### 累加和

In [85]:
a = np.array([[4,1,3],[2,1,5]])
a.cumsum(axis=None)

array([ 4,  5,  8, 10, 11, 16], dtype=int32)

### 累乘积

In [86]:
a.cumprod(axis=None)

array([  4,   4,  12,  24,  24, 120], dtype=int32)

## 简约操作

### 求和

In [87]:
a = np.array([[4,1,3],[2,1,5]])
a.sum(axis=None)

16

### 求积

In [88]:
a.prod(axis=None)

120

### 最小值

In [89]:
a.min(axis=None)

1

### 最大值

In [90]:
a.max(axis=None)

5

### 最小值索引

In [91]:
a.argmin(axis=None)

1

### 最大值索引

In [92]:
a.argmax(axis=None)

5

### 最大间隔

In [93]:
a.ptp(axis=None)

4

### 均值

In [94]:
a.mean(axis=None)

2.6666666666666665

### 标准差

In [95]:
a.std(axis=None)

1.49071198499986

### 方差

In [96]:
a.var(axis=None)

2.2222222222222228

### 是否有非零元素

`a.any()==0`语句是判断阵列中的所有元素是否都为0，当全部为0是，返回真，当有元素不为0时，返回假

In [102]:
a.any()==0

False

#### 是否全部非零


In [104]:
a.all()!=0

True

### 删除生成的文件

In [ ]:
import os
os.remove('foo.csv')
os.remove('file.txt')