# Numpy入门[13]——其他函数
> 参考：
>
> [https://ailearning.apachecn.org/](https://ailearning.apachecn.org/)
>
> 使用Jupyter进行练习

In [1]:
import numpy as np

## 三角函数

```python
sin(x)
cos(x)
tan(x)
sinh(x)
conh(x)
tanh(x)
arccos(x)
arctan(x)
arcsin(x)
arccosh(x)
arctanh(x)
arcsinh(x)
arctan2(x,y) # arctan2(x,y) 返回 arctan(x/y) 
```

## 向量操作

```python

dot(x,y)   # 矩阵乘积
inner(x,y) # 内积运算
cross(x,y) # 外积运算
vdot(x,y)  # 两向量的点积
outer(x,y) # 外积运算
kron(x,y)  # 克罗内克积
tensordot(x,y[,axis]) # 张量乘积

```

## 其他操作

```python
exp(x)
log(x)
log10(x)
sqrt(x)
absolute(x)  # 复数的绝对值。
conjugate(x) # 逐元素返回复共轭。
negative(x)
ceil(x)
floor(x)
fabs(x)      # 逐元素计算绝对值。
hypot(x,y)     # 返回对应点 (x,y) 到原点的距离
fmod(x)      # 返回除法的元素余数
maximum(x,y)
minimum(x,y) 
```

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.hypot(x,y)

array([4.12310563, 5.38516481, 6.70820393])

## 类型处理

```python
iscomplexobj(x)         # 检查复数类型或复数数组
iscomplex(x)            # 返回一个 bool 数组，如果输入元素是复数，则返回 True。
                        # 测试的是输入是否具有非零虚部，而不是输入类型是否为复数。
isrealobj(x)            # 如果 x 不是复数类型或复数数组，则返回 True
isreal(x)               # 同上
imag(x)                 # 返回复数参数的虚部
real(x)                 # 返回复数参数的实部
real_if_close(x)        # 如果输入是复数，所有虚部都接近零，则返回实部
isscalar(x)             # 如果元素的类型是标量类型，则返回 True。
isneginf(x, out=None)   # 逐元素测试负无穷大，将结果作为 bool 数组返回。
isposinf(x, out=None)   # 逐元素测试负无穷大，将结果作为 bool 数组返回。
isinf(x)                # 逐元素测试正无穷或负无穷。
isfinite(x)             # 逐元素测试有限性(不是无穷大，也不是非数字)。
isnan(x)                # 按元素测试 NaN 并将结果作为布尔数组返回。
nan_to_num(x)           # 在数组中将nan(Not A Number)替换为零，并将inf替换为有限数字。
common_type(x)          # 返回输入数组共有的标量类型。
```

In [4]:
print("正无穷：",np.inf)
print("负无穷：",-np.inf)
print("非法值（Not a number）：",np.nan)

正无穷： inf
负无穷： -inf
非法值（Not a number）： nan


In [6]:
# 检查是否为无穷
print("1.0是否为无穷：",np.isinf(1.0))
print("inf是否为无穷：",np.isinf(np.inf))

1.0是否为无穷： False
inf是否为无穷： True


In [7]:
# 非法值
np.array([0]) / 0.0

C:\Users\26969\AppData\Local\Temp\ipykernel_109012\4069785327.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array([0]) / 0.0


array([nan])

只有 0/0 会得到 nan，非0值除以0会得到无穷：

In [8]:
a = np.arange(5.0)
b = a / 0.0
b

C:\Users\26969\AppData\Local\Temp\ipykernel_109012\1104600791.py:2: RuntimeWarning: divide by zero encountered in true_divide
  b = a / 0.0
C:\Users\26969\AppData\Local\Temp\ipykernel_109012\1104600791.py:2: RuntimeWarning: invalid value encountered in true_divide
  b = a / 0.0


array([nan, inf, inf, inf, inf])

nan 与任何数进行比较都是 False：

In [9]:
b == np.nan

array([False, False, False, False, False])

想要找出 `nan` 值需要使用 `isnan`：

In [10]:
np.isnan(b)

array([ True, False, False, False, False])

## 修改形状

```python
atleast_1d
atleast_2d
atleast_3d
expand_dims
apply_over_axes
apply_along_axis
hstack
vstack
dstack
column_stack
hsplit
vsplit
dsplit
split
squeeze
```

## 其他有用函数

```python
fix
mod
amax
amin
ptp
sum
cumsum
prod
cumprod
diff
angle

unwrap
sort_complex
trim_zeros
fliplr
flipud
rot90
diag
eye
select
extract
insert

roots
poly
any
all
disp
unique
nansum
nanmax
nanargmax
nanargmin
nanmin 
```